import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
torch.__version__

'1.12.1+cu102'

# ML Pipepline

Get data ready (tensors) -> Build/pick model (pick optimisation function + build training loop) -> fit model to data and predict -> Evaluate model

# Tensors

Numerical encoding of the input data (audio, text, images..)

## Scalar

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

## Vector

In [6]:
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

## Matrix

In [9]:
matrix = torch.tensor([[1, 2],
                      [2, 2]])
matrix

tensor([[1, 2],
        [2, 2]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[0]

tensor([1, 2])

In [13]:
matrix[1]

tensor([2, 2])

In [14]:
matrix[:1,1]

tensor([2])

## Tensor

In [15]:
tensor_ = torch.tensor([[[1, 2, 3,],
                       [4, 5, 6],
                       [7, 8, 9]]])
tensor_

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
tensor_.shape

torch.Size([1, 3, 3])

In [17]:
tensor_.ndim

3

In [24]:
tensor_[:, :, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
tensor_[:,1,2]

tensor([6])

In [19]:
tensor_[:,:,2]

tensor([[3, 6, 9]])

In [20]:
tensor_[:,2,:]

tensor([[7, 8, 9]])

## Random Tensors

In [21]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3257, 0.9001, 0.7993, 0.3032],
        [0.7649, 0.2473, 0.5909, 0.5149],
        [0.1584, 0.0272, 0.8079, 0.2990]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.4776, 0.7838, 0.6813, 0.7549],
         [0.6100, 0.4156, 0.7086, 0.2469],
         [0.2848, 0.0586, 0.9184, 0.1575]]])

In [24]:
random_tensor.ndim

3

In [25]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # argument: no_of_colour_channels, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and ones

In [26]:
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zero.ndim, zero.shape, zero.dtype

(2, torch.Size([3, 4]), torch.float32)

In [28]:
one = torch.ones(size=(3, 4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
one.ndim, one.shape, one.dtype

(2, torch.Size([3, 4]), torch.float32)

# Range of tensors

In [30]:
torch.range(0, 10) # will be depreciated

<ipython-input-30-d304f6d24824>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10) # will be depreciated


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
torch.arange(0, 10) 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
rand_tensor = torch.arange(start=13, end=20, step=2) 
rand_tensor

tensor([13, 15, 17, 19])

# Tensors like

In [33]:
rand_tensor_bro = torch.zeros_like(rand_tensor)
rand_tensor_bro

tensor([0, 0, 0, 0])

# Tensor datatypes

Thre main ***errors*** you encounter in pytorch:
- Tensor not right datatype (use: `tensor.dtype`)
- Tensor not right shape (use: `tensor.shape`)
- Tensor not on right device (use: `tensor.device`)

In [25]:
float_32_tensor = torch.tensor([2, 1, 2], 
                               dtype=None)
float_32_tensor.dtype

torch.int64

In [26]:
# For more precision, use float 32 or 64. But for 
# faster computation, reduce precision

float_16_tensor = torch.tensor([22, 10, 12], 
                               dtype=torch.float16)
float_16_tensor

tensor([22., 10., 12.], dtype=torch.float16)

In [29]:
float_32_tensor = torch.tensor([2, 1, 2], 
                               dtype=None, # datatype of tensor
                               device='cpu', # What device is your tensor on
                               requires_grad=False) # track your tensor or no

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2., 1., 2.], dtype=torch.float16)

In [31]:
int_16_tensor = torch.tensor([2, 3, 4,], dtype=torch.int16)
float_16_tensor * int_16_tensor

tensor([4., 3., 8.], dtype=torch.float16)

# Operators

In [39]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
tensor * 10

tensor([10, 20, 30])

In [41]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [42]:
tensor - 10

tensor([-9, -8, -7])

In [43]:
tensor % 2

tensor([1, 0, 1])

In [44]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [45]:
torch.dot(tensor, torch.tensor([1, 2, 3]))

tensor(14)

In [46]:
torch.mul(tensor, torch.tensor([1, 2, 3]))

tensor([1, 4, 9])

In [47]:
torch.matmul(tensor, torch.tensor([1, 2, 3]))

tensor(14)

# Tensor Aggregation: Min, max, sum, etc

In [45]:
x = torch.arange(0, 100, 10)

In [46]:
x
# x = x.type(torch.float16)
# x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
torch.min(x)

tensor(0)

In [48]:
torch.max(x)

tensor(90)

In [49]:
torch.mean(x) 

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

### Error because the datatype long is **NOT** supported by `torch.mean()`. 

In [53]:
torch.mean(x.type(torch.float32))

tensor(45.)

# Positional min/max

In [54]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
x.argmin() # index where the min occurs

tensor(0)

In [56]:
x[x.argmin()]

tensor(0)

In [57]:
x[x.argmax()]

tensor(90)

In [58]:
x.argmax()

tensor(9)

# Reshaping, Stacking, Squeezing and Unsqueezing

- reshaping: reshape an i/p tensor to a defined shape
- view: give a new view of the i/p tensor with same memory value
- stacking: to stack tensors (horizontally, vertically, etc)
- squeeze: Remove all `1` dimensions from a tensor
- unsqueeze: Add a `1` dimension to a tensor
- permute: return a view of i/p tensor w/ dimensions permuted (swapped) in a certain way

### Reshaping

In [59]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
x.shape

torch.Size([10])

In [61]:
x_reshaped = x.reshape(1, 3)

RuntimeError: shape '[1, 3]' is invalid for input of size 10

In [62]:
x_reshaped = x.reshape(1, 10)
x_reshaped

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [63]:
x_reshaped = x.reshape(10, 1)
x_reshaped

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [64]:
x_reshaped = x.reshape(2, 5)
x_reshaped

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [65]:
x_reshaped = x.reshape(5, 2)
x_reshaped

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [66]:
x_reshaped.shape

torch.Size([5, 2])

### View

In [67]:
 z = x.view(10)

In [68]:
z

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
z.shape

torch.Size([10])

In [70]:
x.shape

torch.Size([10])

In [71]:
z[0] = 5

In [72]:
z

tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [73]:
z

tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [74]:
x

tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Stack

In [75]:
x_stacked = torch.stack([x, x, x, x])

In [76]:
x_stacked

tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [77]:
x_stacked_2 = torch.vstack([x, x])
x_stacked_2

tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [78]:
x_stacked_3 = torch.hstack([x, x])
x_stacked_3

tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90,  5, 10, 20, 30, 40, 50, 60, 70,
        80, 90])

In [79]:
x_stacked_3 = torch.stack([x, x], dim=0)
x_stacked_3

tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [80]:
x_stacked_3 = torch.stack([x, x], dim=1)
x_stacked_3

tensor([[ 5,  5],
        [10, 10],
        [20, 20],
        [30, 30],
        [40, 40],
        [50, 50],
        [60, 60],
        [70, 70],
        [80, 80],
        [90, 90]])

In [81]:
x_stacked_3 = torch.stack([x, x], dim=2)
x_stacked_3

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

### Squeeze

In [82]:
x_reshaped = x.reshape(1, 10)
x_reshaped.shape

torch.Size([1, 10])

In [83]:
x_reshaped.squeeze()

tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [84]:
x_reshaped.squeeze().shape

torch.Size([10])

In [85]:
x_reshaped.squeeze(dim=1).shape

torch.Size([1, 10])

In [86]:
x_reshaped.squeeze(dim=0).shape

torch.Size([10])

### Permute 
- for images

In [87]:
x_og = torch.rand(size=(224, 224, 3)) # imaginary image
# x_og

In [88]:
x_og.shape

torch.Size([224, 224, 3])

In [89]:
x_permuted = x_og.permute(2, 1, 0)

In [90]:
x_permuted.shape # shape is rearranged

torch.Size([3, 224, 224])

In [91]:
x_og[0, 0, 0] 

tensor(0.6765)

In [92]:
x_permuted[0, 0, 0] = 1000

In [93]:
x_permuted[0, 0, 0]

tensor(1000.)

In [94]:
x_og[0, 0, 0] # value copied to also x_og!!!!

tensor(1000.)

# Indexing

In [95]:
y = torch.arange(1, 10)

In [97]:
y = y.reshape(1, 3, 3)
y

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [98]:
y.shape

torch.Size([1, 3, 3])

In [100]:
y[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [101]:
y[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [102]:
y[0, 1]

tensor([4, 5, 6])

In [103]:
y[0, 1, 0]

tensor(4)

In [104]:
y[0, 2, 0]

tensor(7)

In [113]:
y[-1, -1, -1], y[0, 2, 2], y[:, 2, -1]

(tensor(9), tensor(9), tensor([9]))

In [114]:
# all values of 0 and 1st dimension, but only 1 index value of the 2nd dimension
y[:, :, 1] 

tensor([[2, 5, 8]])

In [117]:
y[0, 2, :]

tensor([7, 8, 9])

In [118]:
y[0, :, 2]

tensor([3, 6, 9])

# Switching between Numpy and PyTorch datatypes

## numpy to pytorch

In [131]:
x = np.arange(1.0, 8.0)
x_tensor = torch.from_numpy(x) 
x, x_tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

####  ! Warning: Here pytorch reflects numpy's default datatype - float64 and not float32 !

In [132]:
x.dtype, x_tensor.dtype

(dtype('float64'), torch.float64)

In [133]:
x_tensor_default = torch.arange(1.0, 8.0)
x_tensor_default.dtype

torch.float32

#### The value of the tensor is not changed if you change the numpy array

In [134]:
x = x + 1
x, x_tensor 

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# Reproducibility in experiments (when using rand)

In [135]:
torch.rand(3, 3) # how to reduce the randomness ?

tensor([[0.0391, 0.3025, 0.0420],
        [0.9542, 0.3008, 0.0088],
        [0.9455, 0.9643, 0.3434]])

In [139]:
# But how?
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9124, 0.5131, 0.1217, 0.8587],
        [0.1427, 0.7842, 0.7094, 0.1651],
        [0.4168, 0.6357, 0.2885, 0.2407]])
tensor([[0.8559, 0.6362, 0.9934, 0.4572],
        [0.6497, 0.8641, 0.3303, 0.0728],
        [0.7043, 0.1171, 0.8389, 0.7696]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [146]:
# Seed it!
# before using the torch.rand() function each time

random_seed = 42

torch.manual_seed(random_seed)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(random_seed)
random_tensor_B = torch.rand(3, 4)


print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Checking GPU access w/ Pytorch

In [147]:
!nvidia-smi

Tue Nov 22 14:27:48 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P0    21W /  N/A |   1475MiB /  5926MiB |     32%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Check availability

In [148]:
torch.cuda.is_available()

True

### Device agnostic setup

In [51]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

#---------------
# In scripts:
#---------------
# import argparse
# import torch

# parser = argparse.ArgumentParser(description="Write Description Here")
# parser.add_argument('--disable-cuda', action='store_true',
#                     help='Disable CUDA')
# args = parser.parse_args()
# args.device = None
# if not args.disable_cuda and  torch.cuda.is_available():
#     args.device = torch.device('cuda')
# else:
#     args.device = torch.device('cpu')

cuda


### Count number of devices availble

In [52]:
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

In [53]:
x = torch.tensor([1,2,3])
print(x, x.device)

tensor([1, 2, 3]) cpu


In [54]:
x_on_gpu = x.to(device)

In [55]:
x_on_gpu.device

device(type='cuda', index=0)

### Moving tensors back to cpu

In [56]:
x_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [57]:
x_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

#### !!! numpy doesn't work on gpu. So you need to move the tensor to cpu to use numpy computations

In [58]:
x_on_cpu = x_on_gpu.to('cpu')
print(x_on_cpu, x_on_cpu.device)

tensor([1, 2, 3]) cpu


In [59]:
x_on_cpu.numpy()

array([1, 2, 3])